feat(docker-manifest): apply additional image tags with crane
mirkolenz/flocken pull request #51
Opened 2024-07-07 21:56 UTC by cameronraysmith

Hello @mirkolenz. Many thanks for flocken!
I have been using it for several months and found it to be very helpful.

When building somewhat larger images, pushing each tag in a manner that verifies the contents of each layer can take a long time.
This PR proposes to push the first tag in `_tags` with buildah and then apply subsequent tags with [crane](https://search.nixos.org/packages?channel=unstable&show=crane), which does not separately verify the hash of each layer and is thus significantly faster in my experience.

- [x] apply additional tags to images using `crane tag` instead of `buildah manifest push` 

Two potential drawbacks to consider are 

* this requires logging in via crane in addition to buildah since crane stores credentials, for example, in `$HOME/.docker/config.json` instead of `$XDG_CONFIG_DIR/containers/auth.json`
* presumably there is some robustness associated to verifying all the layer hashes when applying new tags

I think these are reasonable tradeoffs for the improved performance, but, of course, happy to discuss further if you disagree.
I may be biased since I tend to require building relatively large images.

2024-07-07 22:00 UTC, cameronraysmith commented on src/docker-manifest.nix
>            for tag in ${builtins.toString _tags}; do
Note that `crane tag` is idempotent so it isn't really necessary to use `builtins.tail` or some other approach to remove the first tag from `_tags`; though there might be other reasons to prefer that approach.

2024-07-07 22:12 UTC, cameronraysmith commented
I tested the image push in [CI on my fork](https://github.com/cameronraysmith/flocken/actions/runs/9830253071/job/27136228695).

2024-07-08 08:49 UTC, mirkolenz requested changes
Thanks for the PR! I think this is an excellent change that should greatly reduce CI times for larger images with many tags. I added two minor comments, once these are addressed, I am happy to merge the changes and release a new version 😄

2024-07-08 08:49 UTC, mirkolenz commented on src/docker-manifest.nix
> +          firstTag=${builtins.head _tags}
Could you move this to a pure nix definition before the actual script?

`firstTag = builtins.head _tags`

Then you can use standard variable substitution when calling buildah and crane.

2024-07-08 08:49 UTC, mirkolenz commented on src/docker-manifest.nix
>            for tag in ${builtins.toString _tags}; do
Thanks for the info! Maybe we should also add a small comment so that this knowledge is not lost in the future?

2024-07-08 19:35 UTC, cameronraysmith commented on src/docker-manifest.nix
>            for tag in ${builtins.toString _tags}; do
00b0b64c21cc97b5ca42fc3b4edf33a44d9ba242

2024-07-08 19:38 UTC, cameronraysmith commented
Many thanks for your review! I have included both suggestions in the updates. Feel free to let me know if you think of anything else.

2024-07-09 07:13 UTC, mirkolenz approved these changes
Great, everything looks good to me! Thank you once again for this nice PR 😄

2024-07-09 07:14 UTC, merged